controllers:
    resource: '../src/Controller/'
    type:     annotation

app_random_name:
    path: /name/random
    controller: App\Controller\LuckyController::name

 # blog_list:
 #     path: /blog
 #     controller: App\Controller\BlogController::list

# api_post_show:
#     path:       /api/posts/{id}
#     controller: App\Controller\BlogApiController::show
#     methods:    GET|HEAD
#
# api_post_edit:
#     path:       /api/posts/{id}
#     controller: App\Controller\BlogApiController::edit
#     methods:    PUT
#
#
#     # config/routes.yaml
# contact:
#     path:       /contact
#     controller: 'App\Controller\DefaultController::contact'
#     condition:  "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"
#     # expressions can also include config parameters:
#     # condition: "request.headers.get('User-Agent') matches '%app.allowed_browsers%'"
#
# # config/routes.yaml
# blog_show:
#     path:       /blog/{slug}
#     controller: App\Controller\BlogController::show
#
# # config/routes.yaml
# blog_list:
#     path:       /blog/{page}
#     controller: App\Controller\BlogController::list
#     defaults:
#         page: 1
#     requirements:
#         page: '\d+'
#
# blog_show:
#     path:       /blog/{slug}
#     controller: App\Controller\BlogController::show
